### ISSUE TITLE
NBN_Connection layout is cache unfriendly

### ISSUE THREAD

**Issue by Phireh** [nathhB/nbnet#21]
[__NBN_Connection](https://github.com/nathhB/nbnet/blob/adf4b9c25508c18060062ea0624adfc1358324b5/nbnet.h#L814) is big enough (a little above 1 MB per connection) that it doesn't fit into the L2 cache of many systems.

A quick look into a frequently called function like [Connection_ReadNextMessageFromStream](https://github.com/nathhB/nbnet/blob/adf4b9c25508c18060062ea0624adfc1358324b5/nbnet.h#L3303) shows that `channels` and `endpoint` are accessed often and immediately after each other, however, their positions in the struct are very far apart. On my Linux 64b system they look like this:

```
(gdb) p offsetof(NBN_Connection, channels)
$1 = (NBN_Channel *(*)[32]) 0x107318
```

```
(gdb) p offsetof(NBN_Connection, endpoint)
$2 = (struct __NBN_Endpoint **) 0x30
```

More than a MB apart. I believe this is introducing cache misses and impacting performance. The fix is very straightforward: move frequently used members of the struct closer together.

**Comment by nathhB** [comment]
@Phireh hey, do you want to do this one?

**Comment by nathhB** [comment]
Merged this PR: https://github.com/nathhB/nbnet/pull/26
