### ISSUE TITLE
Segfault when restarting nbnet

### ISSUE THREAD

**Issue by lenne18** [nathhB/nbnet#22]
Calling NBN_GameServer_Start or NBN_GameClient_Start after calling NBN_GameServer_Stop and NBN_GameClient_Stop, respectively, causes a segfault when [allocating memory for pooling.](https://github.com/nathhB/nbnet/blob/adf4b9c25508c18060062ea0624adfc1358324b5/nbnet.h#L1768)

To reproduce the bug, put the calls in a RAII class/struct like so:
```
struct GameServer
{
    GameServer() { NBN_GameServer_Start(PROTOCOL_NAME, PORT, false); }
    ~GameServer() { NBN_GameServer_Stop(); }
};
```
Then in the main loop (using raylib):
```
// For simplicity's sake, I use GameServer here
// but should be an interface to switch between GameServer or GameClient
std::unique_ptr<GameServer> networkState; 

// Other code

while (!window.ShouldClose())
{
    // Other code

    // Toggle the network state using F1
    if ( IsKeyPressed(KEY_F1) )
    {
        if (networkState)
            networkState.reset();
        else
            networkState.reset(new GameServer());
    }
    // Rest of the code
}
```
Pressing F1 thrice should give a segfault.

**Comment by nathhB** [comment]
Fixed by commit [cfeaa6bb3ee33896b377884f71f2f7b4b8d7b8b5](https://github.com/nathhB/nbnet/commit/cfeaa6bb3ee33896b377884f71f2f7b4b8d7b8b5)
