### ISSUE TITLE
Need help building raylib example

### ISSUE THREAD

**Issue by lesleyrs** [nathhB/nbnet#55]
I don't understand cmake well enough to follow a single step apparently:

```
This driver requires the code to be compiled with emscripten.

emcmake cmake -DRAYLIB_LIBRARY_PATH=<path to raylib lib file> -DRAYLIB_INCLUDE_PATH=<path to raylib headers folder> .
```
So I do:
emcmake cmake -DRAYLIB_LIBRARY_PATH="../../../raylib-web/src/libraylib.a"
 -DRAYLIB_INCLUDE_PATH="../../../raylib-web/src/" .

It can find the headers but gives me this even though it exists:
cannot find -l../../../raylib-web/src/libraylib.a: No such file or directory

Isn't it supposed to be -lraylib anyway? Regardless after hours of trying nothing works...

PS: I'm on windows with mingw makefiles

**Comment by nathhB** [comment]
@lesleyrs can you try using absolute paths?

**Comment by lesleyrs** [comment]
Then I get: `libraylib.a: error adding symbols: file format not recognized`

I have already used it for emscripten without nbnet though.

**Comment by nathhB** [comment]
@lesleyrs it looks like your libraylib.a was not built for the right target. Are you sure you built raylib with emscripten?

**Comment by lesleyrs** [comment]
Yes I'm sure because I've already been building with emscripten to host on itchio, regardless both on Windows and Linux I get the same `file format` error now.

**Comment by nathhB** [comment]
@lesleyrs this error is a linker error stating that the architecture from which libraylib.a was built does not match the one you are trying to compile for. I suggest that you try rebuilding raylib with the same version of emcc that you are trying to compile the nbnet example with.

**Comment by lesleyrs** [comment]
Ok I managed to get it to build on Linux after far too much time and I still don't fully get the problem 😮‍💨. These were the problems I encountered:

1: On both platforms I got
```
/home/azureuser/dev/nbnet/examples/raylib/../../nbnet.h:4985:9: error: call to undeclared function 'clock_gettime'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 4985 |     if (clock_gettime(CLOCK_MONOTONIC_RAW, &tp) < 0)
      |         ^
/home/azureuser/dev/nbnet/examples/raylib/../../nbnet.h:4985:23: error: use of undeclared identifier 'CLOCK_MONOTONIC_RAW'
 4985 |     if (clock_gettime(CLOCK_MONOTONIC_RAW, &tp) < 0)
```

I saw raylib does this `    #define _POSIX_C_SOURCE 199309L     // Required for: CLOCK_MONOTONIC if compiled with c99 without gnu ext.
` so I changed -std=c99 to gnu99 and that made the program run but it crashes.

2: I got emscripten from apt on Linux because I thought it was a recent version, but nope it's 3.1.5 instead of 3.1.50, big difference. It was missing a glfw function definition.

3: full paths were needed to find libraylib like you said, and I dont' even remember what I did to get the file format error.

**Comment by nathhB** [comment]
@lesleyrs I'm glad you figured it out. I fixed the README.
